theme = "autophugo"
baseURL = "https://rosamariarinaldi.it/"
languageCode = "en-us"
title = "Rosa Maria Rinaldi"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Author]
    name = "Rosa Maria Rinaldi"
    email = "rosamariarinaldi@fastwebnet.it"

[params]
# Meta
    description = "Rosa Maria Rinaldi"
    keywords = "phugo, hugo, photogallery, photoblog, hugo theme"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    thumb_quality = 100
    #full_width = 960
    full_quality = 90
    #column_count = 4
    
    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"
    
    # Footer panel
    [params.footer]
    video = '<iframe width="560" height="315" src="https://www.youtube.com/embed/OauDrCZjB8c" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
    
    [params.footer.paragraph]
    headline = "Rosa Maria Rinaldi"
    text = """**BIO**

**ITA** - Vive e lavora a Milano 
Liceo classico. Laurea in lettere e filosofia alla Statale di Milano, tesi in storia dell’arte. Giornalismo specializzato in arte, architettura e design.
La pittura. Qualsiasi segno primitivo o contemporaneo, che manifesti spontaneità di gesto, colore, composizione, diventa riferimento. Nascono i primi disegni: la forma è ottenuta dall’uso del colore, sciolto col calore della mano e steso con le dita. Le categorie di tempo e spazio saltano, come nei sogni. Alla pittura si aggiunge la fotografia. Architetture e paesaggi, fotografati, scomposti, sovrapposti, ricomposti, dipinti. Atlanti e mappe fatti a pezzi e incollati su tela in modo casuale. Grandi tele in bianco e nero. Colore e disegni si associano in libero equilibrio. Voli, danze, movimenti, salti, balzi e corse percorrono le tele su fondi rossi, viola e rosa accesi, verde primavera, gialli dorati. Dal 2019 ad oggi, “MUSICA/ PITTURA ”:  una serie di lavori basati sulla ricerca della trasformazione del suono in colore e sull’interscambio delle arti, considerate entrambe fondamento per l’armonia dell’universo. 


**ENG** - Classical high school. Degree in literature and philosophy from the University of Milan, thesis in art history. Journalism specializing in art, architecture and design.
Painting. Any primitive or contemporary sign, which manifests spontaneity of gesture, color, composition, becomes a reference. The first drawings are born: the shape is obtained from the use of color, melted with the warmth of the hand and spread with the fingers. The categories of time and space jump, as in dreams. Photography is added to painting. Architectures and landscapes, photographed, broken down, superimposed, recomposed, painted. Atlases and maps torn apart and glued on canvas in a random way. Large black and white canvases. Color and designs come together in free balance. Flights, dances, movements, jumps, leaps and races run through the canvases on bright red, purple and pink backgrounds, spring green, golden yellows. From 2019  to today, the "PAINTED MUSIC" cycle: a series of works based on the search for the transformation of sound into color and the interchange of arts, both considered the foundation for the harmony of the universe. Under the same vault of a night sky, a single sign of color combines music and painting. The invisible notes wander in the ether, soliciting a sound dialogue with the viewer.




**EXHIBITIONS**

- 2020 MENEGHETTI INTERNATIONAL ART PRIZE'19.
- 2019 CIRCUITI DINAMICI Milano
- 2018 INDART/ villa reale/MONZA
- 2018 TRIENNALE/MILANO
- 2017 DIMORE E DESIGN/ PALAZZO TERZI BERGAMO
- 2016 ADGALLERY/ Milano 
- 2014 FINALISTA PREMIO TERNA 06/ TORINO
- 2013 ERMANNO CRISTINI, Varese
- 2012 DUET /duetart Varese 
- 2010 BIENNALE DI ARCHITETTURA, Venezia/Spazio Tethis
- 2010 GALLERIA TOSELLI, con Corrado Levi, Milano 
- 2010 PIO MONTI Gallery, MIART
- 2009 PIO MONTI Gallery, MIART 
- 2009 LIMEN ARTE, Vibo Valencia
- 2009 GALLERIA LUISE DELLE PIANE Milano
- 2009 UNIVERSITA' BOCCONI, Milano
- 2009 COSE MAI VISTE, Roma (a cura di ACHILLE BONITO OLIVA)
- 2008 GALLERIA FRANCO TOSELLI 
- 2007 GALLERIA ERMANNO TEDESCHI, Milano 
- 2001 GALLERIA  JANNONE, Milano (personale)
- 2000 That’s Amore/FABBRICA EOS, Milano 
- 1998 VITA GALLERY, Pechino (personale)
- 1997 Polam Lau, Lecadre Gallery, Honk Kong 
- 1995 GALLERIA JANNONE, Milano (personale)
"""
    [params.footer.social]
    headline = "Follow me"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "http://instagram.com/rosamariarinaldi"
    icon = "fa-instagram"

    [[params.footer.social.links]]
    label = "Facebook"
    url = "https://www.facebook.com/profile.php?id=100000120516466&sk=about"
    icon = "fa-facebook"

    [[params.footer.social.links]]
    label = "mail"
    url = "mailto:rosamariarinaldi@fastwebnet.it"
    icon = "fa-envelope"

    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = true # Set this to true if you don't want to have a contact form on your site
    realEmail = "example@example.org"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "Philippe Scorsolini"
